title: HongLi Wang's Homepage
page-top-title: HongLi Wang
top-section-bg-text: Computer Science
home-subtitle: HongLi Wang&ensp;|&ensp;王泓理
copyright-text: '&copy; HongLi Wang 2024-2025. All Rights Reserved.'
